services:
  phpipam-web:
    image: phpipam/phpipam-www:latest
    ports:
      - 8456:80 # <Host Port>:<Container Port>
    environment:
      - TZ=Europe/Bratislava  #TimeZone
      - IPAM_DATABASE_HOST=phpipam-mariadb  #IP or Docker Container Name of Maria DB
      - IPAM_DATABASE_PASS=ChangeMe #Password to Database
      - IPAM_DATABASE_WEBHOST=%
      - IPAM_DISABLE_INSTALLER=1
      - IPAM_TRUST_X_FORWARDED=true
    restart: unless-stopped
    volumes:
      - phpipam-logo:/phpipam/css/images/logo
      - phpipam-ca:/usr/local/share/ca-certificates:ro
    depends_on:
      - phpipam-mariadb

  phpipam-cron:
    image: phpipam/phpipam-cron:latest
    environment:
      - TZ=Europe/Bratislava
      - IPAM_DATABASE_HOST=phpipam-mariadb 
      - IPAM_DATABASE_PASS=Change Me #Password to Database
      - SCAN_INTERVAL=1h
    restart: unless-stopped
    volumes:
      - phpipam-ca:/usr/local/share/ca-certificates:ro
    depends_on:
      - phpipam-mariadb

  phpipam-mariadb:
    image: mariadb:latest
    environment:
      - MYSQL_ROOT_PASSWORD=ChangeMe  #Password to Database
    restart: unless-stopped
    volumes:
      - phpipam-db-data:/var/lib/mysql

volumes:
  phpipam-db-data:
  phpipam-logo:
  phpipam-ca: